version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CRYPTO_KEY=qKG6nnv7VXVSA4pDotDyWNx8ca5mKxWkn0eL784GxKQ=
      - CRYPTO_IV=k3vi7ZFUB8/XSID2AXEwug==
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
